### ISSUE TITLE
How did you get it?

### ISSUE THREAD

**Issue by JackGraymer** [5ah1n/CS50_Python#1]
Hey there, finishing CS50P here,

I just wanted to know how did you downloaded all the exercises, or did you code it locally?

I did it with github spaces and submitted them directly. In github there is 1 repo but every exercise is a branch, so 40 branches or so.

Did you manage to download them all at once? if so, how?

**Comment by sahinyes** [comment]
Hello friend,

I did it using github spaces. You just need to select all the files on codespace with "ctrl + a" and right-click then click on download. 

I have attached an image to make it clearer.

![](https://cdn-images-1.medium.com/max/1000/1*H29uZgi8prKhFVPL_gIcUQ.png)

**Comment by JackGraymer** [comment]
yeah, I thought so, but the problem is that after submitting, I deleted and
modified some folders to avoid the clutter, so the idea would be to
download the submissions.
Any ideas?
